### ISSUE TITLE
Missing requirement for using cognito auth for web.

### ISSUE THREAD

**Issue by rcfrias** [aws/amazon-cognito-auth-js#11]
I think it is important to mention that in the app client settings at the cognito console, **"Implicit grant"** has to be enabled.  Otherwise the authentication will fail no matter what the user does.

**Comment by dinvlad** [comment]
It could also be "Authorization code", in which case you'd need to use `auth.useCodeGrantFlow();` as specified in the example, and then submit an XHR to /oauth2/authorize with returned `code` in body and `state` in `Authorization: Basic <state>` header.

**Comment by dinvlad** [comment]
For a regular web app, it could also be "Authorization code", in which case you'd need to use auth.useCodeGrantFlow(); as specified in the example, and then POST a request from your backend to /oauth2/token with code in the body and state in Authorization: Basic <state> header. There are a few more parameters, for details see the first example in http://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html.

Implicit flow (appropriate for client-side apps) will return access and id tokens valid for 1 hour, while authorization code flow (for server-side apps) would also give you a refresh token that you could reuse for a configurable time (sorry if this is already obvious, just wanted to throw in my 2c).

**Comment by rcfrias** [comment]
Good extra info. I think both scenarios must be clearly explained in the docs, as right now its too ambiguous and non-self-explanatory.
