### ISSUE TITLE
/oauth2/authorize redirects to empty error

### ISSUE THREAD

**Issue by mymattcarroll** [aws/amazon-cognito-auth-js#124]
`https://MY_APP.auth.ap-southeast-2.amazoncognito.com/oauth2/authorize?redirect_uri=https%3A%2F%2FMY_APP_DOMAIN%2Fcallback&response_type=token&client_id=MY_CLIENT_ID&state=STATE&scope=openid%20email`  has suddenly started redirecting to empty error.

See screen shot below.

Is anyone else having this issue?

I am 99.9% sure that it is not a configuration issue as this has started happening for all 3 applications we have using this SDK. They were all working 24 hours ago and have suddenly started redirecting to this empty error screen.

![image](https://user-images.githubusercontent.com/16235788/39412557-af329636-4c61-11e8-95e2-3b1a134f791a.png)

**Comment by mymattcarroll** [comment]
@yuntuowang It seems this issue has something to do with Cognito cookies not being cleared after running the `cognitoAuth.signout()` function. Here is the response so far from AWS Support:

> What happens is that the /oauth2/authorize works when there is valid unexpired cookies in the browser session. You can replicate this by visiting the URL with /login:

> https://things-in-motion.auth.ap-southeast-2.amazoncognito.com/login?redirect_uri=https%3A%2F%2Ftim.portal.thingsinmotion.io%3A443%2Fcallback&response_type=code&client_id=25c6k37b2q5kun44sp527jqog7&state=J4DPr83xhtMqsweSA0mghFSq3uofqQXr&scope=

> Use the login box to authenticate yourself. Once you have been authenticated and your browser has valid unexpired cookies, if you visit the URL (below) with /oauth2/.. URI, it will work and redirects you to the URL that you have specified in your Userpool configuration.

> https://things-in-motion.auth.ap-southeast-2.amazoncognito.com/oauth2/authorize?redirect_uri=https%3A%2F%2Ftim.portal.thingsinmotion.io%3A443%2Fcallback&response_type=code&client_id=25c6k37b2q5kun44sp527jqog7&state=J4DPr83xhtMqsweSA0mghFSq3uofqQXr&scope=

**Comment by ankon** [comment]
https://github.com/Collaborne/amazon-cognito-auth-js/commit/54d0e454f3f42957e722ef7a248df89fc91d6347 . 

I've changed dependencies in our `package.json` so that we get this change:
```diff
diff --git a/package.json b/package.json
index dc1f74a..e26934b 100644
--- a/package.json
+++ b/package.json
@@ -32,7 +32,7 @@
-    "amazon-cognito-auth-js": "^1.1.5",
+    "amazon-cognito-auth-js": "https://github.com/Collaborne/amazon-cognito-auth-js#collaborne",

```

**Comment by andrewcharlton** [comment]
:+1: We are encountering this issue as well.  The change to /login works.

We'll fork for now but would appreciate this being fixed.

**Comment by yuntuowang** [comment]
Hi, there was some issue with our recent deployment. We have rolled back the changes. Now /oauth2/authorize endpoint should work! Thanks!

**Comment by ankon** [comment]
@yuntuowang thanks. With "rolled back" you mean something on the server-side? 

I'm a bit concerned about this issue, as it essentially made our application inaccessible for our users for a long time, and I couldn't see anything on the usual AWS channels about it (http://status.aws.amazon.com specifically).

**Comment by yuntuowang** [comment]
Now the /oauth2/authorize hosted UI urls works as expected.

**Comment by timwhunt** [comment]
@ankon in some cases like this we notify customers via the Personal Health Dashboard as that is more direct than the Service Health Dashboard.

**Comment by ankon** [comment]
@timwhunt A-ha! Found it there! Yet another place to add to the list of "what to check when customers are unhappy".
