### ISSUE TITLE
How to run this app?

### ISSUE THREAD

**Issue by AMiggel** [aws/amazon-cognito-auth-js#134]
Please, help me, i need run this app and i don't know how to do it.

**Comment by AMiggel** [comment]
@yuntuowang

**Comment by yuntuowang** [comment]
Hi @AMiggel, we currently don't have support for react native. 

You can use the Sample of the SDK to use the SDK. https://github.com/aws/amazon-cognito-auth-js/tree/master/sample      You can follow the instructions in Readme.md and the comments in index.html.  

Also, AWS Amplify team provides react support: https://github.com/aws/aws-amplify/tree/master/packages/aws-amplify-react/src/Auth
