### ISSUE TITLE
Is it possible to use and redirect to a non-secure URL before and after login?

### ISSUE THREAD

**Issue by davestewart** [aws/amazon-cognito-auth-js#166]
Or do I need to set up SSL on my machine before attempting to develop locally?

**Comment by mikiAdSecure** [comment]
I don't think it's possible, I set up a local cert to be able to develop locally, it'll take you 10 minutes: https://medium.com/@richardr39/using-angular-cli-to-serve-over-https-locally-70dab07417c8

**Comment by davestewart** [comment]
@mikiAdSecure - hey, thanks for the link!

I'll check it out now

**Comment by chamathsilva** [comment]
you don't have to set up SSL.  Cognito allows redirecting non-secure URL if it is localhost. 
for example, you can use non-secure URL such as `http://localhost:3000`,  `http:localhost:3000/logincallback`

**Comment by davestewart** [comment]
Oh really!? I'll check that out now :)

**Comment by davestewart** [comment]
OK, I solved it!

I didn't realise that all the URLs had to match ones in the control panel on AWS.

A back end dev was handling that.

He also didn't realises that you could use `http://localhost` so everybody's learnt something!

😄
