### ISSUE TITLE
Invalid IdentityPool Configuration Exception

### ISSUE THREAD

**Issue by Ch3ck** [aws/amazon-cognito-auth-js#167]
This question is related to CUP, IDPs and IAM roles.
After creating a new CUP and IDP, proceeded with adding them to IAM Trust policy for the assumed I AM Role. I keep getting this error: 

`Invalid identity pool configuration. Check assigned IAM roles for this pool`

I've explored this problem for hours and my understanding is it has to do with the IAM role Trust policy attached to the execution role for this Identity Pool. Any ideas will be greatly appreciated.

**Comment by Ch3ck** [comment]
Issue fixed

**Comment by gowreswaran** [comment]
@Ch3ck May i know how you fixed this issue? I'm running into the same issue now.

**Comment by Ch3ck** [comment]
@gowreswaran Add the Cognito IDP ID as a resource to your IAM role and add it to the IAM trust policy as well, this error should go away.
