### ISSUE TITLE
The CookieStorage src file is not included in the packaged software at npm

### ISSUE THREAD

**Issue by ottokruse** [aws/amazon-cognito-auth-js#174]
The CookieStorage src file is not included in the packaged software at npm (e.g. not present in folder lib, es)

**Comment by manueliglesias** [comment]
Hi @ottokruse 

Can you confirm you see them in the latest version? (1.3.1 as of now)

**Comment by ottokruse** [comment]
I just updated to amazon-cognito-auth-js@1.3.2 and do indeed now see the file.
Thanks
