### ISSUE TITLE
How to handle token refresh?

### ISSUE THREAD

**Issue by kocur4d** [aws/amazon-cognito-auth-js#175]
I am aware that there are few similar issues but they are left unanswered.

My use case is that I would like to check for a token valid on every graphql call I am making:

```
  const auth = getAuth()
  const user = auth.getCachedSession()
  if(!user.isValid())
    auth.refreshSession(auser.getRefreshToken().getToken())
  const session = auth.getSignInUserSession()
  const token = session.getIdToken().getJwtToken() 
```

But this doesn't work after an hour I am getting:

<img width="478" alt="screen shot 2019-02-04 at 15 59 31" src="https://user-images.githubusercontent.com/1427354/52220082-f197b400-2895-11e9-8ef8-b751ec02860f.png">

This call fails with `'Invalid JWT Token - TokenExpiredError: jwt expired'` from my server and the token gets updated for a next call.

`awaiting` `auth.refreshSession()` doesn't do anything and checking the source indeed confirms the need for  `auth.userhandler` `onSuccess` method.

How can you go around it? I would like to only check, if token is valid, and update it when making calls that are using them.

**Comment by AntonioBusillo** [comment]
Hello @kocur4d how did you handle the token refresh?
