### ISSUE TITLE
React script build is failing with v1.3.1

### ISSUE THREAD

**Issue by Hugodby** [aws/amazon-cognito-auth-js#186]
I am using amplify v1.1.19 with react 16.2.0 (react script). Build is failing since yesterday because of the new v1.3.1 version. I receive the following error:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/amazon-cognito-auth-js/es/DecodingHelper.js:1:7

Read more here: http://bit.ly/2tRViJ9
```

Fixed by reverting `amazon-cognito-auth-js` to v1.1.9 in the package-lock.json file.

**Comment by yashwanthkumarsuruneni** [comment]
I was using `uglifyjs-webpack-plugin` switched to `terser-webpack-plugin` works fine
