### ISSUE TITLE
This page trying to load scripts from unauthenticated sources

### ISSUE THREAD

**Issue by konstantinvlasenko** [aws/amazon-cognito-auth-js#2]
Hi,
Please ask someone to fix https://d3oia8etllorh5.cloudfront.net/20170430200719/css/cognito-login.css
It uses **http** (instead of https)  http://fonts.googleapis.com/css?family=Roboto

This triggers the warning message in the browser.

Posted here https://forums.aws.amazon.com/thread.jspa?threadID=257082&tstart=0 as well

**Comment by itrestian** [comment]
Thank you for bringing this up. We are aware of the issue and we will deploy a fix.

**Comment by itrestian** [comment]
This was fixed.
