### ISSUE TITLE
signout feature

### ISSUE THREAD

**Issue by guylichtman** [aws/amazon-cognito-auth-js#25]
Hi,

I am doing a simple test via the sample web page: 
https://github.com/aws/amazon-cognito-auth-js/tree/master/sample

 I noticed that I am getting an error on signout. Signout is basically redirecting to a url of the following format:

`https://<domain>.auth.us-east-1.amazoncognito.com/logout?logout_uri=<logouturl>&client_id=<client_id>`

And then I get an error stating:

`Required String parameter 'redirect_uri' is not present`

I assume the redirect is used to clear the cookies, but it seems to be failing. I tried playing with this a bit by changing `logout_uri` to `redirect_uri` but couldn't get it to redirect back to my logout uri.

**Comment by rcfrias** [comment]
redirect is the uri used to go after auth signs-in/out, and it has to be the same uri that you use when you request the auth.  It is like a contract to double check it is the right auth logic.

I would suggest to double check your settings vs your client config. 

This is a working config:

```
private initCognitoSDK(){
    let authData = {
      ClientId : this.config.clientId, // Your client id here
      AppWebDomain : this.config.appWebDomain,
      TokenScopesArray : this.config.tokenScopesArray,
      RedirectUriSignIn : this.config.redirectUriSignIn,
      RedirectUriSignOut : this.config.redirectUriSignOut
    };
    return new AWSCognito.CognitoIdentityServiceProvider.CognitoAuth(authData);
  }
```

And the example config:

```
{
  "base_url": "https://localhost:3004/",
  "clientId": "your_app_id_configured_at_the_console",
  "appWebDomain": "your_project.auth.us-east-1.amazoncognito.com",
  "tokenScopesArray": ["phone", "email", "profile","openid", "aws.cognito.signin.user.admin"],
  "redirectUriSignIn": "https://localhost:3000/", // <- this has to match the App config in cognito.
  "redirectUriSignOut": "https://localhost:3000/" // <- this has to match the App config in cognito.
}
```

*I would test this until getting a working example, then modify as needed.

**Comment by guylichtman** [comment]
Thanks. I got it working. I configured the logout url wrong in the user pool configuration (basically had a typo in the url). 

The error message returned is such a case is really misleading and I think it can be improved. 

Anyway, I am closing the issue.

**Comment by shnplr** [comment]
When using /logout/client_id=<app.client.id>&redirect_uri=<redirect_uri> the error message is:

Required String parameter 'response_type' is not present

**Comment by Elayaraja-Dhanapal** [comment]
Hi,

When user clicks on logout button,
My code is as below for logout from cognito,

var xhttp = new XMLHttpRequest();
if (this.readyState == 4 && this.status == 200) {
	console.log(this.responseText);
}
var url = https://<domain>.auth.us-east-1.amazoncognito.com/logout?logout_uri=https://s3-eu-west-1.amazonaws.com/<bucketName>/<html>&client_id=<client_id>

xhttp.open("GET", url, true);
xhttp.send();

I am getting CORS issue when GET request is called.

Can anybody help me to fix this?

Thank you in advance!

**Comment by jdrydn** [comment]
Trying the `signOut`, I keep getting an error regarding the `logout_uri` parameter in Cognito: "_Required String parameter 'redirect_uri' is not present_"

https://github.com/aws/amazon-cognito-auth-js/blob/acd6affe9f4bb4856b7181ad2e7105d846cea5e4/src/CognitoAuth.js#L94

Looks like this now needs to be renamed to `redirect_uri`? I'm guessing Cognito has been updated internally to use `redirect_uri` consistently, but this library is behind?
