### ISSUE TITLE
Code Auth - getCodeQueryParameter(httpRequestResponse)

### ISSUE THREAD

**Issue by vtuhtan** [aws/amazon-cognito-auth-js#29]
I have an issue with Code Auth method. While parsing response it can't establish a session, it constantly requests a new code.

I receive a code in format: domain/page?code=<code_value>

From the [Code](https://github.com/aws/amazon-cognito-auth-js/blob/master/src/CognitoAuth.js#L411) it splits the url using the following regex: /#(.+)/ which cannot extract _code_ value because it is not after poundsign, it's after questionmark.

**Comment by coakeson** [comment]
I am having the same issue with the 1.0.0 version from npm.

**Comment by modmac** [comment]
https://github.com/aws/amazon-cognito-auth-js/pull/32 fixes that

**Comment by yuntuowang** [comment]
Now you can use npm to install the latest 1.1.0 version which fixed the issue. Thanks!
