### ISSUE TITLE
The authorization_code method is parsing URL incorrectly and sending blank body and header

### ISSUE THREAD

**Issue by coakeson** [aws/amazon-cognito-auth-js#31]
Should be this:
CognitoAuth.js:107 "QUERYPARAMETERREGEX1: /\?(.+)/,"
CognitoAuth.js:507 "for (j in header) {"
CognitoAuth.js:510 "for (i in body) {"

Without those changes, the authorization_code method will not work as the body and header are not populated, and the code cannot be parsed out of the URL

**Comment by modmac** [comment]
PR https://github.com/aws/amazon-cognito-auth-js/pull/32 resolves this issue.
