### ISSUE TITLE
Please release fixes recently merged

### ISSUE THREAD

**Issue by jwiggins78** [aws/amazon-cognito-auth-js#41]
I see that a PR was merged fixing code grant flow recently, but there are no new versions actually released via npm.  Please make a 1.0.1 with current fixes!

Also, there was an issue importing your module.  Same happens in a new react app using create-react-app.  Please review package.json and ensure that your index.js is referenced properly.

**Comment by colletts** [comment]
Yes can you do this please so I don't have to install this manually

**Comment by g-combs** [comment]
Please do, as this appears as an issue for a lot of people including us.

**Comment by comfroels** [comment]
@yuntuowang Please can you do an npm release for all of us?

**Comment by yuntuowang** [comment]
Done! Now you can use npm to get the latest version 1.0.1.

**Comment by comfroels** [comment]
Yay! that is awesome!

**Comment by itrestian** [comment]
Closing this as changes were released.

**Comment by yuntuowang** [comment]
Now you can use npm to get the latest version 1.1.0.
