### ISSUE TITLE
Can't resolve 'amazon-cognito-auth-js'

### ISSUE THREAD

**Issue by sam-jg** [aws/amazon-cognito-auth-js#42]
This is happening on a regular create react app, not related to typescript like #39.

**Comment by deeperid** [comment]
In package.json: 
`
  "main": "lib/index.js",
  "module": "es/index.js",
`
Are nowhere to be found in amazon-cognito-auth, so I used:

`import { CognitoAuth } from 'amazon-cognito-auth-js/dist/amazon-cognito-auth';`

To work around the incorrect values in package.json for now

**Comment by yuntuowang** [comment]
Is your project using React structure?
If yes, this is the correct way to do: import { CognitoAuth } from 'amazon-cognito-auth-js/dist/amazon-cognito-auth';

**Comment by jaxondu** [comment]
Still encounter this error following the documentation. This issue should not be closed. If what you said is the right way to import, then please correct the documentation so that we do not waste time searching through all the past issues.

**Comment by yuntuowang** [comment]
@jaxondu The documentation shows how to use SDK generally. For specific case such as using React structure,  import { CognitoAuth } from 'amazon-cognito-auth-js/dist/amazon-cognito-auth';
should be the correct way. And this is the common sense for importing when using React structure.

**Comment by jaxondu** [comment]
@yuntuowang Sorry I'm using VueJS. It is not common sense to have ES import in this manner. You must have export it wrongly.

**Comment by yuntuowang** [comment]
Hi @jaxondu, I just updated the README.md for the ES modules import:
// ES Modules, e.g. transpiling with Babel
import {CognitoAuth} from 'amazon-cognito-auth-js/dist/amazon-cognito-auth';
If you have any other concerns, feel free to post here, thanks!

**Comment by yuntuowang** [comment]
I have updated this workaround: import { CognitoAuth } from 'amazon-cognito-auth-js/dist/amazon-cognito-auth';  in our README.md.

**Comment by bloomdido** [comment]
The workaround/update to the README.md file seems to have reverted back in v1.1.1.

**Comment by yuntuowang** [comment]
Hi @bloomdido, we didn't include anything change about import SDK in v1.1.1. 
Do you mean that the workaround/update in the README.md doesn't work?  Thanks.

**Comment by bloomdido** [comment]
The README file is incorrect.

```
import {CognitoAuth} from 'amazon-cognito-auth-js'
```
...doesn't work. The correct ES6 import is:
```
import {CognitoAuth} from 'amazon-cognito-auth-js/dist/amazon-cognito-auth'
```

This was correct in the README file until commit 1fbcae4d42480297bfa6bab77c47d8d6a51c5332.

**Comment by yuntuowang** [comment]
Thanks a lot for pointing this out!! @bloomdido I just updated README.md with the correct version.

**Comment by sunsoori** [comment]
which programming language is this
https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUserPools.html
Can you point to any sample code which uses this? 
I'm trying to use this in a lambda function.

**Comment by engharb** [comment]
@yuntuowang I have a problem in my Ionic+angular+typescript Mobile Project. I want to 
```
import {CognitoAuth} from 'amazon-cognito-auth-js/dist/amazon-cognito-auth'
```
But it does not recognize it?
