### ISSUE TITLE
parseCognitoWebResponse with useCodeGrantFlow() only works on Chrome

### ISSUE THREAD

**Issue by megyfexid** [aws/amazon-cognito-auth-js#46]
On Safari and Firefox the makePOSTRequest at the end of getCodeQueryParameter inside parseCognitoWebResponse always fails with "error": "invalid_grant". This causes an infinite loop of parseCognitoWebResponse constantly requesting new code tokens.

Oddly it works fine on Chrome but fails on the other browsers.

**Comment by megyfexid** [comment]
Sorry my mistake.

I didn't realise getSession and parseCognitoWebResponse are both asynchronous functions.

Reading the source code is your friend. :)

**Comment by mlisonek98** [comment]
I have this issue as well, how did you end up solving it?
