### ISSUE TITLE
Sample index.html issues

### ISSUE THREAD

**Issue by crissupb** [aws/amazon-cognito-auth-js#5]
It seems that the sample and SDK are not in alignment as to case of the following parameters.  The sample code uses PascalCase and the SDK is expecting camelCase.

Fails
TokenScopesArray : '<TODO: your scope array here>',
RedirectUriSignIn : '<TODO: your redirect url when signed in here>',
RedirectUriSignOut : '<TODO: your redirect url when signed out here>'

Works
tokenScopesArray : '<TODO: your scope array here>',
redirectUriSignIn : '<TODO: your redirect url when signed in here>',
redirectUriSignOut : '<TODO: your redirect url when signed out here>'

**Comment by mryanmurphy** [comment]
Looks like this was fixed in 78b5d1
