### ISSUE TITLE
Space missing between "Continue with" and "Google" on Cognito Page

### ISSUE THREAD

**Issue by expatiating** [aws/amazon-cognito-auth-js#51]
It is unclear if this is controlled by this project or another Amazon Service, but the following should be fixed. There is a space missing between "Continue with" and "Google" on Cognito Login page. See image below (red circle highlighting the issue)

![space missing between continue with and google](https://user-images.githubusercontent.com/3590621/33465061-85fa11e6-d5fa-11e7-9770-59c6553e3471.png)

**Comment by behrooziAWS** [comment]
Thanks for reporting @expatiating, it's service side and we'll fix with the next deployment.

**Comment by expatiating** [comment]
👍  Thanks for the quick reply - look forward to it!
