### ISSUE TITLE
The Authetication wouldn't work in incognito mode.

### ISSUE THREAD

**Issue by bhao-speedline** [aws/amazon-cognito-auth-js#57]
I got the authentication work in normal mode, but it failed in incognito mode all the time. I'm wondering whether it's supposed to fail in incognito mode or I didn't do it correctly.

**Comment by itrestian** [comment]
Any particular error you are getting? Can you try with the unminified versions of the libraries and Google Chrome Developer Tools and see what error you are getting?

**Comment by bhao-speedline** [comment]
@itrestian I found the reason for the failure. I called getSession() immediately after I called parseCognitoWebResponse(), and at that time, the makePOSTRequest() hadn't got the response yet. It's weird that it only failed in incognito mode. Thanks anyways.

**Comment by itrestian** [comment]
Sounds good, so issue can be closed?
