### ISSUE TITLE
'amazon-cognito-auth-js' is not in the npm registry.

### ISSUE THREAD

**Issue by Leon-Africa** [aws/amazon-cognito-auth-js#6]
Hello Team,

Running command npm install --save amazon-cognito-auth-js 

returns 404:

npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/amazon-cognito-auth-js
npm ERR! 404 
npm ERR! 404  'amazon-cognito-auth-js' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! Please include the following file with any support request:
npm ERR!     [/Users/xxxxx/Documents/cognitjs_test_npm/npm-debug.log](url)

LOG (npm-debug.log):

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'amazon-cognito-auth-js' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose config Skipping project config: /Users/xxxxx/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData amazon-cognito-auth-js
9 silly fetchNamedPackageData amazon-cognito-auth-js
10 silly mapToRegistry name amazon-cognito-auth-js
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry data Result {
13 silly mapToRegistry   raw: 'amazon-cognito-auth-js',
13 silly mapToRegistry   scope: null,
13 silly mapToRegistry   escapedName: 'amazon-cognito-auth-js',
13 silly mapToRegistry   name: 'amazon-cognito-auth-js',
13 silly mapToRegistry   rawSpec: '',
13 silly mapToRegistry   spec: 'latest',
13 silly mapToRegistry   type: 'tag' }
14 silly mapToRegistry uri https://registry.npmjs.org/amazon-cognito-auth-js
15 verbose request uri https://registry.npmjs.org/amazon-cognito-auth-js
16 verbose request no auth needed
17 info attempt registry request try #1 at 8:51:11 AM
18 verbose request id f29fef7b0628a2db
19 http request GET https://registry.npmjs.org/amazon-cognito-auth-js
20 http 404 https://registry.npmjs.org/amazon-cognito-auth-js
21 verbose headers { 'content-type': 'application/json',
21 verbose headers   'cache-control': 'max-age=0',
21 verbose headers   'content-length': '2',
21 verbose headers   'accept-ranges': 'bytes',
21 verbose headers   date: 'Fri, 09 Jun 2017 06:51:13 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   age: '0',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lhr6337-LHR',
21 verbose headers   'x-cache': 'MISS',
21 verbose headers   'x-cache-hits': '0',
21 verbose headers   'x-timer': 'S1496991074.540145,VS0,VE375',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 404,
22 silly get   { 'content-type': 'application/json',
22 silly get     'cache-control': 'max-age=0',
22 silly get     'content-length': '2',
22 silly get     'accept-ranges': 'bytes',
22 silly get     date: 'Fri, 09 Jun 2017 06:51:13 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     age: '0',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lhr6337-LHR',
22 silly get     'x-cache': 'MISS',
22 silly get     'x-cache-hits': '0',
22 silly get     'x-timer': 'S1496991074.540145,VS0,VE375',
22 silly get     vary: 'Accept-Encoding' } ]
23 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/amazon-cognito-auth-js
23 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
23 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
23 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
23 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
23 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
23 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
23 silly fetchPackageMetaData     at emitOne (events.js:96:13)
23 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
23 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
23 silly fetchPackageMetaData  error for amazon-cognito-auth-js { Error: Registry returned 404 for GET on https://registry.npmjs.org/amazon-cognito-auth-js
23 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
23 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
23 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
23 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
23 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
23 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
23 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
23 silly fetchPackageMetaData     at emitOne (events.js:96:13)
23 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
23 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
23 silly fetchPackageMetaData   pkgid: 'amazon-cognito-auth-js',
23 silly fetchPackageMetaData   statusCode: 404,
23 silly fetchPackageMetaData   code: 'E404' }
24 silly rollbackFailedOptional Starting
25 silly rollbackFailedOptional Finishing
26 silly runTopLevelLifecycles Finishing
27 silly install printInstalled
28 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/amazon-cognito-auth-js
28 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
28 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
28 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
28 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:187:22)
28 verbose stack     at emitTwo (events.js:106:13)
28 verbose stack     at Request.emit (events.js:191:7)
28 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1048:10)
28 verbose stack     at emitOne (events.js:96:13)
28 verbose stack     at Request.emit (events.js:188:7)
28 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:969:12)
29 verbose statusCode 404
30 verbose pkgid amazon-cognito-auth-js
31 verbose cwd /Users/xxxxx/Documents/cognitjs_test_npm
32 error Darwin 16.5.0
33 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "amazon-cognito-auth-js"
34 error node v6.10.2
35 error npm  v3.10.10
36 error code E404
37 error 404 Registry returned 404 for GET on https://registry.npmjs.org/amazon-cognito-auth-js
38 error 404
39 error 404 'amazon-cognito-auth-js' is not in the npm registry.
40 error 404 You should bug the author to publish it (or use the name yourself!)
41 error 404 Note that you can also install from a
42 error 404 tarball, folder, http url, or git url.
43 verbose exit [ 1, true ]

**Comment by Leon-Africa** [comment]
After npm install -g npm

npm install --save amazon-cognito-auth-js
npm ERR! code E404
npm ERR! 404 Not Found: amazon-cognito-auth-js@latest

**Comment by rcfrias** [comment]
Yeah, found the same here, although I think this is an error in the docs. I think the aws guy was trying to say "identity" instead of "auth", who knows, he might have been in a rush.

**Comment by rcfrias** [comment]
nvm amazon-cognito-auth.js is not included in the dist folder of amazon-cognito-identity.  This needs attention from AWS, for now Im copy/pasting from dist to dist.

**Comment by rcfrias** [comment]
any plans to update the registry for amazon-cognito-auth-js ?

**Comment by paulfryer** [comment]
Docs say to do this:

`> npm install --save amazon-cognito-auth-js
`
NPM says this: 

**npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/amazon-cognito-auth-js**

**Comment by dinvlad** [comment]
+1, currently we have to use
```
import { CognitoAuth } from 'amazon-cognito-auth-js/dist/amazon-cognito-auth';
```
in TypeScript/Babel

**Comment by itrestian** [comment]
The library is in npm at this point.
