### ISSUE TITLE
How to use Sync service with federated users?

### ISSUE THREAD

**Issue by joe455** [aws/amazon-cognito-auth-js#63]
I want to use sync service for federated users. Can someone shed some light on this. May be example/doc?

**Comment by yuntuowang** [comment]
Hi @joe455, we have many resources about sync service.
For how the service works: http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sync.html
For the API reference: http://docs.aws.amazon.com/cognitosync/latest/APIReference/Welcome.html
Also, if you want to use Cognito Sync in an Android or iOS application, you will probably want to make API calls via the AWS Mobile SDK. 
Android: http://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/cognito-sync.html
iOS: http://docs.aws.amazon.com/mobile/sdkforios/developerguide/cognito-sync-data-across-devices-for-ios.html
