### ISSUE TITLE
No https:// in the AppDomain

### ISSUE THREAD

**Issue by jrbrodie77** [aws/amazon-cognito-auth-js#67]
Minor issue, but following the sample app, I got tripped up at the AppDomain entry.  If I copy and paste from the console, I end up with https:// with the domain name.  It would be great if the redundant https could be ignored.

from sample/index.html...

	function initCognitoSDK() {
		var authData = {
            ClientId : '6kkj6umf6mp1r2l1923r2am9n0',
			AppWebDomain : 'https://foobar.auth.us-west-2.amazoncognito.com',
			..........

**Comment by yuntuowang** [comment]
Yes, the "https://" is not included in the app domain. If you see the CognitoAuth.js source code, you will see it. I will update the index.html sample app too!
