### ISSUE TITLE
TokenScopesArray? What goes here?

### ISSUE THREAD

**Issue by jesseSharedit** [aws/amazon-cognito-auth-js#8]
TokenScopesArray : '<TODO: your scope array here>',

I am assuming valid entries are the same from the App Client Settings 

TokenScopesArray : ['phone', 'email', 'profile','openid', 'aws.cognito.signin.user.admin'],

**Comment by mryanmurphy** [comment]
Those are the correct entries.

**Comment by glb** [comment]
Perhaps
```
TokenScopesArray: ['<TODO: your scope array here, try "phone", "email", ...>'],
```
would be a more helpful example? Or putting in the full set as defaults with a `// TODO: customize if desired` comment?

**Comment by yuntuowang** [comment]
@glb @jesseSharedit both provided great suggestions. I have updated README.md to clarify how to initiate scope array.

**Comment by glb** [comment]
@yuntuowang Thank you!
