### ISSUE TITLE
Keep getting redirect_mismatch

### ISSUE THREAD

**Issue by iamcootis** [aws/amazon-cognito-auth-js#85]
I have my app just like explained in #13 

My Request URL looks like this: https://xxMyAppxx.auth.us-east-1.amazoncognito.com/oauth2/authorize?redirect_uri=https%3A%2F%2Flocalhost%3A4200%2Flogin&response_type=token&client_id=<<myclientid>>&state=nhaxExm6ojeV9AmNxacNCm9DAh1r7DWC&scope=email%20profile%20openid&identity_provider=Google

![capture](https://user-images.githubusercontent.com/521754/35759956-7ee81dd8-0842-11e8-95e0-16e723ec2924.PNG)

What am I doing wrong?

**Comment by iamcootis** [comment]
It never fails, as soon as I write up a ticket, I solve it myself. The callbackUrl() function was returning something different that I had set up in my Cognito User Pool.

**Comment by leonachan1** [comment]
@iamcootis I got the same issue. can you share how to solve it in detail?
The error occurs only on machine that has never signed in to cognito before.

**Comment by schof** [comment]
@iamcootis I'm running into the same issue. Can you elaborate on what you mean by `callbackUrl` function? Also what is the exact syntax for the value you used in the Cognito User Pool? Thanks.

**Comment by ysweid** [comment]
@schof You need to set the Callback URLs in the `User Pool > App integration > App client settings` 

URLs have to be absolute (e.g https://domain.com/...)

Hope this helps the people who get here!

**Comment by calboru** [comment]
Can't we use http://localhost:4200 for development purposes?

**Comment by ysweid** [comment]
@calboru I'm not sure about localhost being a callback url, but what you can do is to expose the localhost to the internet by using [ngrok](https://ngrok.com/)

`ngrok http 4200`

P.S ngrok creates HTTPS endpoint as well.

**Comment by uforiginal** [comment]
I'm also having this issue, but it happens no matter what I set my callback url to. I've tried just having it callback to https://www.google.com just to try and get it working and I'm getting a redirect mismatch every time. Is there some extra setting that I'm missing because from what I understand this is supposed to be incredibly simple. :/
