### ISSUE TITLE
Permit identity provider (name or id) in CognitoAuth.getCognitoConstants()

### ISSUE THREAD

**Issue by Nogbit** [aws/amazon-cognito-auth-js#9]
Are you up for pull requests?  I would like to specify an Identity name or id in the [getCognitoConstants()](https://github.com/aws/amazon-cognito-auth-js/blob/37414f50b523d7b235ebc8fdebcb09ef704ee9d7/src/CognitoAuth.js#L66) method and have the user skip the identity provider selection process (cognito hosted UI) and instead make sure the  `/authorize` endpoint routes directly to a specified `identity_provider` login as detailed in the [authorization endpoin docs](http://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html).

It would probably be one line of code really in that method as well as the method that builds the FQDN.

**Comment by yuntuowang** [comment]
Thanks for the comment. You can go ahead to send a pull request. We will later review your added code and decide to merge or not.

**Comment by rafalwrzeszcz** [comment]
#22 should already solve this.

**Comment by Nogbit** [comment]
Thanks!
