### ISSUE TITLE
Where to input Identity pool ID?

### ISSUE THREAD

**Issue by Jun711** [aws/amazon-cognito-auth-js#96]
I got login using Facebook working but I can only see the user data in the user pool but not the identity pool. Then, I noticed Identity pool ID wasn't included in the configuration at all. Where should I include it? Thanks

https://github.com/Jun711/amazon-cognito-auth-js/blob/social-login/sample/index.html

Thanks

**Comment by yutingguo** [comment]
you need to integrate your userpool with your identity pool, check the use case 17 in the following sdk:
https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js

**Comment by Jun711** [comment]
Thanks @gwander
